apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  nginx.conf: |
    worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;
        keepalive_timeout 10m;
        proxy_connect_timeout  600s;
        proxy_send_timeout  600s;
        proxy_read_timeout  600s;
        fastcgi_send_timeout 600s;
        fastcgi_read_timeout 600s;
        #HTTP server
      server {
            listen       80;
            server_name  proxydemo.mywebsite.com;
            location / {
                proxy_pass https://demo.mywebsite.com:443;
            }
        }
    }