apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-web-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Text Page</title>
    </head>
    <body>
      <h1>Hello World!</h1>
    </body>
    </html>