apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: hello-world-helm
spec:
  destination:
    name: ''
    namespace: 'my-nginx-helm'
    server: 'https://kubernetes.default.svc'
  source:
    path: ./taslak/apps/helm/hello-world-helm
    repoURL: >-
      https://github.com/ahmetceyhan/ArgoCD.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: hello-world-helm-project
