apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: vault
spec:
  destination:
    name: ''
    namespace: 'my-vault'
    server: 'https://kubernetes.default.svc'
  source:
    path: ./taslak/apps/helm/vault-helm
    repoURL: >-
      https://github.com/ahmetceyhan/ArgoCD.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: vault-helm-project
