apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: '*'
#  We used * to encompass different namespaces for all Helm applications. Example: "my-vault"
    server: 'https://kubernetes.default.svc'
  source:
    path: ./taslak/apps/helm
    repoURL: >-
      https://github.com/ahmetceyhan/ArgoCD.git
    targetRevision: HEAD
# Only the main directory(./taslak/apps/helm) is added to ArgoCD, subdirectories are not added.
#    directory:
#      recurse: true
  sources: []
  project: helm-project

